import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/header/header'
import { Footer } from '@/components/footer/footer'
import { useRouter } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
